// exercicios-web/react/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react';

import './Calculator.css'
import Button from '../components/Button'
import Display from '../components/Display'

export default class Calculator extends Component {

    clearMemory() {
        console.log("limpar")
    }

    setOperation(operation) {
        console.log(operation)
    }

    addDigit(n) {
        console.log(n)
    }

    render() {

        const adicionarDigit = n => this.addDigit(n)
        const setOperation = op => this.setOperation(op)

        return (
            <div className="calculator">
                <Display value={10000000} />
                <Button label={"AC"} triple click={() => this.clearMemory()}></Button>
                <Button label={"/"} operation click={setOperation}></Button>
                <Button label={"7"} click={n => this.addDigit(n)}></Button>
                <Button label={"8"} click={n => this.addDigit(n)}></Button>
                <Button label={"9"} click={n => this.addDigit(n)}></Button>
                <Button label={"*"} operation  click={setOperation}></Button>
                <Button label={"4"} click={n => this.addDigit(n)}></Button>
                <Button label={"5"} click={n => this.addDigit(n)}></Button>
                <Button label={"6"} click={n => this.addDigit(n)}></Button>
                <Button label={"-"} operation  click={setOperation}></Button>
                <Button label={"1"} click={n => this.addDigit(n)}></Button>
                <Button label={"2"} click={n => this.addDigit(n)}></Button>
                <Button label={"3"} click={n => this.addDigit(n)}></Button>
                <Button label={"+"} operation  click={setOperation}></Button>
                <Button label={"0"} double click={n => this.addDigit(n)}></Button>
                <Button label={"."} click={n => this.addDigit(n)></Button>
                <Button label={"="} operation  click={setOperation}></Button>
            </div>
        )
    }
}

// exercicios-web/vue/calculator/src/main/Calculator.vue
<template>
    <div class="calculator">
        <Display value="1000"/>
        <Button label="AC" triple @onClick="clearMemory"/>
        <Button label="/" operation @onClick="setOperation"/>
        <Button label="7" @onClick="addDigit"/>
        <Button label="8" @onClick="addDigit"/>
        <Button label="9" @onClick="addDigit"/>
        <Button label="*" operation @onClick="setOperation"/>
        <Button label="4" @onClick="addDigit"/>
        <Button label="5" @onClick="addDigit"/>
        <Button label="6" @onClick="addDigit"/>
        <Button label="-" operation @onClick="setOperation"/>
        <Button label="1" @onClick="addDigit"/>
        <Button label="2" @onClick="addDigit"/>
        <Button label="3" @onClick="addDigit"/>
        <Button label="+" operation @onClick="setOperation"/>
        <Button label="0" @onClick="addDigit" double/>
        <Button label="."  @onClick="addDigit" />
        <Button label="=" operation @onClick="setOperation"/>
    </div>
</template>

<script>
import Display from "../components/Display"
import Button from "../components/Button"

export default {
    components: { Button, Display },
    methods: {
        clearMemory() {
            // console.log("Limpar")
        },
        setOperation(operation) {
            // console.log("operation: ",operation )
        },
        addDigit(n) {
            // console.log("Digito: ", n)
        }
    }
}
</script>

<style>
    .calculator {
        height: 320px;
        width: 235px;
        border-radius: 5px;
        overflow: hidden;
        
        display: grid;
        grid-template-columns: repeat(4, 25%);
        grid-template-rows: 1fr 48px 48px 48px 48px;
    }
</style>
